# Generated by Django 4.1.4 on 2023-03-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoustip',
            name='incident_time',
        ),
    ]
