# Generated by Django 4.1.4 on 2023-03-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
        ('comment', '0001_initial'),
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='police.police'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen'),
        ),
    ]
